<?php 
    $template = 'var templateUrlPhoneListCtrl = "'.$this->url('application/default').'";';
	$this->headScript()->appendScript($template,  'text/javascript');

	$template = 'var templateUrlPhoneDetailCtrl = "'.$this->url('application/default', array('controller' => 'index', 'action' => 'edit')).'";';
	$this->headScript()->appendScript($template,'text/javascript');

	$template = 'var phonesUrl = "'.$this->url('application/default', array('controller' => 'index', 'action' => 'phones')).'";';
	$this->headScript()->appendScript( $template, 'text/javascript');

	$this->headScript()->appendFile($this->basePath().'/js/application/app.js','text/javascript');
	$this->headScript()->appendFile($this->basePath().'/js/application/controllers.js','text/javascript');
 ?>


