<script type="text/javascript">
	var phonecatApp = angular.module('phonecatApp', ['ngRoute',  'phonecatControllers']);

	phonecatApp.config(['$routeProvider',
	  function($routeProvider) {
	    $routeProvider.
	      when('/', {
	        templateUrl: 'http://localhost/zend2Angular/public/application/index/index',
	        controller: 'PhoneListCtrl'
	      }).
	      when('/edit/:phoneId', {
	        templateUrl: 'http://localhost/zend2Angular/public/application/index/edit',
	        controller: 'PhoneDetailCtrl'
	      }).
	      otherwise({
	        redirectTo: '/'
	      });	     
	  }]);

	'use strict';

	var phonecatControllers = angular.module('phonecatControllers', []);

	phonecatControllers.controller('PhoneListCtrl', ['$scope', '$http',
	  function($scope, $http) {
	    $http.get('http://localhost/zend2Angular/public/application/index/phones').success(function(data) {
	      $scope.phones = data;
	    });

	    $scope.orderProp = 'age';
	  }]);


    phonecatControllers.controller('PhoneDetailCtrl', ['$scope', '$routeParams', '$http',
	  function($scope, $routeParams, $http) {
	    $http.get('http://localhost/zend2Angular/public/application/index/phones/' + $routeParams.phoneId).success(function(data) {
	      $scope.phone = data;
	    });
	  }]);
    

</script>


