<div class="row">
     <div class="col-md-6" ng-controller="PhoneListCtrl">
    Search: <input ng-model="query">
    Sort by:
    <select ng-model="orderProp">
        <option value="name">Alphabetical</option>
        <option value="age">Newest</option>
    </select>
      <ul>
        <ul class="phones">
          <li ng-repeat="phone in phones | filter:query | orderBy:orderProp">
            <a href="#/edit/{{phone.id}}">{{phone.name}}</a>
          </li>
        </ul>
      </ul>
    </div>
</div>
